 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/player_seasons", type: :request do
  # PlayerSeason. As you add validations to PlayerSeason, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PlayerSeason.create! valid_attributes
      get player_seasons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      player_season = PlayerSeason.create! valid_attributes
      get player_season_url(player_season)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_player_season_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      player_season = PlayerSeason.create! valid_attributes
      get edit_player_season_url(player_season)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PlayerSeason" do
        expect {
          post player_seasons_url, params: { player_season: valid_attributes }
        }.to change(PlayerSeason, :count).by(1)
      end

      it "redirects to the created player_season" do
        post player_seasons_url, params: { player_season: valid_attributes }
        expect(response).to redirect_to(player_season_url(PlayerSeason.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PlayerSeason" do
        expect {
          post player_seasons_url, params: { player_season: invalid_attributes }
        }.to change(PlayerSeason, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post player_seasons_url, params: { player_season: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested player_season" do
        player_season = PlayerSeason.create! valid_attributes
        patch player_season_url(player_season), params: { player_season: new_attributes }
        player_season.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the player_season" do
        player_season = PlayerSeason.create! valid_attributes
        patch player_season_url(player_season), params: { player_season: new_attributes }
        player_season.reload
        expect(response).to redirect_to(player_season_url(player_season))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        player_season = PlayerSeason.create! valid_attributes
        patch player_season_url(player_season), params: { player_season: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested player_season" do
      player_season = PlayerSeason.create! valid_attributes
      expect {
        delete player_season_url(player_season)
      }.to change(PlayerSeason, :count).by(-1)
    end

    it "redirects to the player_seasons list" do
      player_season = PlayerSeason.create! valid_attributes
      delete player_season_url(player_season)
      expect(response).to redirect_to(player_seasons_url)
    end
  end
end
