 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/weeks", type: :request do
  # Week. As you add validations to Week, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Week.create! valid_attributes
      get weeks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      week = Week.create! valid_attributes
      get week_url(week)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_week_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      week = Week.create! valid_attributes
      get edit_week_url(week)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Week" do
        expect {
          post weeks_url, params: { week: valid_attributes }
        }.to change(Week, :count).by(1)
      end

      it "redirects to the created week" do
        post weeks_url, params: { week: valid_attributes }
        expect(response).to redirect_to(week_url(Week.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Week" do
        expect {
          post weeks_url, params: { week: invalid_attributes }
        }.to change(Week, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post weeks_url, params: { week: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested week" do
        week = Week.create! valid_attributes
        patch week_url(week), params: { week: new_attributes }
        week.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the week" do
        week = Week.create! valid_attributes
        patch week_url(week), params: { week: new_attributes }
        week.reload
        expect(response).to redirect_to(week_url(week))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        week = Week.create! valid_attributes
        patch week_url(week), params: { week: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested week" do
      week = Week.create! valid_attributes
      expect {
        delete week_url(week)
      }.to change(Week, :count).by(-1)
    end

    it "redirects to the weeks list" do
      week = Week.create! valid_attributes
      delete week_url(week)
      expect(response).to redirect_to(weeks_url)
    end
  end
end
